name: ledagracerasmussen
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Leda Grace Rasmussen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#2f3943'
    - '#8f9b97'
    - '#ffffff'
    - '#f2ca94'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
